name: Build Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BrokenDreamCI: "true"   # 设置环境变量

    steps:
      - name: Print env
        run: echo "BrokenDreamCI is $BrokenDreamCI"

      - uses: actions/checkout@v5.0.0

      - name: Set JDK
        uses: actions/setup-java@v5.0.0
        with:
          distribution: temurin
          java-version: 21

      - name: Chmod execution permission
        run: chmod +x gradlew

      - name: Build apk
        run: ./gradlew assembleRelease

      - name: Upload apk
        uses: actions/upload-artifact@v4.6.2
        with:
          name: UniAppx
          path: app/build/outputs/apk/release/*.apk